name: file_browser
description: "flutter文件浏览器"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  fc_native_video_thumbnail: ^0.17.2
  ffi: ^2.1.3
  flutter:
    sdk: flutter

  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg